import type { MessageCatalog } from '../message-keys'

export const enUS = {
  'app.name': 'MiawPOS',
  'app.caption': 'Your workspace',
  'locale.label': 'Bahasa / Language',
  'locale.shortLabel': 'Language',
  'login.title': 'Sign in to MiawPOS',
  'login.google': 'Continue with Google',
  'session.loading': 'Checking your session…',
  'session.title': 'Your account',
  'session.description': 'You are signed in to MiawPOS.',
  'session.active': 'Session active',
  'session.accountId': 'Account ID',
  'session.details': 'Account information',
  'session.detailsDescription': 'The account currently connected to this workspace.',
  'session.placeholderTitle': 'You are connected',
  'session.placeholderBody': 'Account access is available. Operational features are not available in this version yet.',
  'session.logout': 'Sign out',
  'session.loggingOut': 'Signing out…',
  'session.sharedDevice': 'Finished using a shared device? Sign out of your account.',
  'nav.account': 'Account',
  'nav.label': 'Main navigation',
  'nav.menu': 'Open navigation',
  'nav.close': 'Close navigation',
  'nav.skip': 'Skip to content',
  'notFound.title': 'Page not found',
  'notFound.body': 'Check the page address or return to your account.',
  'notFound.back': 'Go back',
  'action.retry': 'Try again',
  'feedback.login.title': 'Unable to sign in',
  'feedback.login.body': 'Unable to connect with Google. Please try again.',
  'feedback.expired.title': 'Your session has ended',
  'feedback.expired.body': 'Sign in again to continue.',
  'feedback.logout.title': 'You have signed out',
  'feedback.logout.body': 'Your account session has ended.',
  'feedback.denied.title': 'Access denied',
  'feedback.denied.body': 'You do not have access to this action. Contact your administrator.',
  'feedback.unavailable.title': 'Action unavailable',
  'feedback.unavailable.body': 'This action is unavailable right now. Contact your administrator.',
  'feedback.validation.title': 'Check your details',
  'feedback.validation.body': 'Complete or correct the highlighted fields.',
  'feedback.required': 'This field is required.',
  'feedback.invalid': 'Enter a valid value.',
  'feedback.network.title': 'Unable to connect',
  'feedback.network.body': 'Check your connection and try again. The action could not be confirmed.',
  'feedback.request.title': 'Unable to complete the action',
  'feedback.request.body': 'Check your details or contact your administrator.',
  'feedback.system.title': 'Something went wrong',
  'feedback.system.body': 'The action could not be confirmed. Try again or contact your administrator.',
  'feedback.contract.title': 'Unable to process the response',
  'feedback.contract.body': 'Contact your administrator if this continues. The action could not be confirmed.',
  'feedback.reference': 'Support reference: {requestId}',
} satisfies MessageCatalog
