import type { MessageCatalog } from '../message-keys'

export const enUS = {
  'sale.cash': "Cash sale",
  'sale.quantity': "Quantity",
  'sale.tender': "Cash received (Rupiah)",
  'sale.confirmBody': "Confirm the sale after receiving cash. The total and change are determined when the sale is posted.",
  'sale.pendingBody': "The sale is not confirmed. Retry the same transaction; do not reload or close the tab until the result is known.",
  'sale.pendingTitle': "Sale not confirmed",
  'sale.resume': "Resume pending sale",
  'sale.retry': "Check / retry the same transaction",
  'sale.post': "Confirm cash payment",
  'sale.posting': "Processing payment…",
  'sale.detail': "Sale details",
  'sale.loading': "Loading sale…",
  'sale.posted': "Sale posted",
  'sale.reversed': "Sale reversed and refund recorded",
  'sale.reference': "Sale reference",
  'sale.total': "Total",
  'sale.change': "Change",
  'sale.refund': "Cash refund",
  'sale.reverse': "Reverse sale",
  'sale.reverseBody': "Reversal records a full cash refund and preserves the sale history. Ensure the cash is returned to the buyer.",
  'sale.reason': "Reversal reason",
  'sale.reverseConfirm': "Confirm reversal and refund",
  'sale.reversing': "Processing reversal…",
  'sale.refresh': "Check current status",
  'sale.missing': "Sale not found in this workspace.",
  'sale.alreadyReversed': "The sale has already been reversed. Check its current status before continuing.",
  'sale.conflict': "A different transaction uses the same reference. Check the original transaction before creating another sale.",
  'sale.insufficient': "Cash received does not cover the sale total. Check the amount received.",
  'catalog.missing': "Item not found in this workspace.",
  'catalog.unsellable': "This item has no active selling price.",
  'catalog.new': 'Add item',
  'catalog.name': 'Item name',
  'catalog.price': 'Price (Rupiah)',
  'catalog.priceHelp': 'A positive whole number. Leave empty for an item that is not yet for sale.',
  'catalog.save': 'Save item',
  'catalog.saving': 'Saving…',
  'catalog.detail': 'Item details',
  'catalog.loading': 'Loading item…',
  'catalog.unpriced': 'No selling price yet',
  'root.loading': 'Loading workspaces…',
  'root.new': 'Create your first workspace',
  'root.newBody': 'Name your workspace to start using MiawPOS.',
  'root.name': 'Workspace name',
  'root.nameHelp': 'Up to 200 characters.',
  'root.create': 'Create workspace',
  'root.creating': 'Creating…',
  'root.check': 'Check for an existing workspace',
  'root.select': 'Choose a workspace',
  'root.switch': 'Switch workspace',
  'root.workspace': 'Workspace',
  'root.open': 'Open workspace',
  'root.ready': 'Your workspace is ready.',
  'app.name': 'MiawPOS',
  'app.caption': 'Your workspace',
  'locale.label': 'Bahasa / Language',
  'locale.shortLabel': 'Language',
  'login.title': 'Sign in to MiawPOS',
  'login.google': 'Continue with Google',
  'session.loading': 'Checking your session…',
  'session.title': 'Your account',
  'session.description': 'You are signed in to MiawPOS.',
  'session.active': 'Session active',
  'session.accountId': 'Account ID',
  'session.details': 'Account information',
  'session.detailsDescription': 'The account currently connected to this workspace.',
  'session.placeholderTitle': 'You are connected',
  'session.placeholderBody': 'Account access is available. Operational features are not available in this version yet.',
  'session.logout': 'Sign out',
  'session.loggingOut': 'Signing out…',
  'session.sharedDevice': 'Finished using a shared device? Sign out of your account.',
  'nav.account': 'Account',
  'nav.label': 'Main navigation',
  'nav.menu': 'Open navigation',
  'nav.close': 'Close navigation',
  'nav.skip': 'Skip to content',
  'notFound.title': 'Page not found',
  'notFound.body': 'Check the page address or return to your account.',
  'notFound.back': 'Go back',
  'action.retry': 'Try again',
  'feedback.login.title': 'Unable to sign in',
  'feedback.login.body': 'Unable to connect with Google. Please try again.',
  'feedback.expired.title': 'Your session has ended',
  'feedback.expired.body': 'Sign in again to continue.',
  'feedback.logout.title': 'You have signed out',
  'feedback.logout.body': 'Your account session has ended.',
  'feedback.denied.title': 'Access denied',
  'feedback.denied.body': 'You do not have access to this action. Contact your administrator.',
  'feedback.unavailable.title': 'Action unavailable',
  'feedback.unavailable.body': 'This action is unavailable right now. Contact your administrator.',
  'feedback.validation.title': 'Check your details',
  'feedback.validation.body': 'Complete or correct the highlighted fields.',
  'feedback.required': 'This field is required.',
  'feedback.invalid': 'Enter a valid value.',
  'feedback.network.title': 'Unable to connect',
  'feedback.network.body': 'Check your connection and try again. The action could not be confirmed.',
  'feedback.request.title': 'Unable to complete the action',
  'feedback.request.body': 'Check your details or contact your administrator.',
  'feedback.system.title': 'Something went wrong',
  'feedback.system.body': 'The action could not be confirmed. Try again or contact your administrator.',
  'feedback.contract.title': 'Unable to process the response',
  'feedback.contract.body': 'Contact your administrator if this continues. The action could not be confirmed.',
  'feedback.reference': 'Support reference: {requestId}',
} satisfies MessageCatalog
