export const idID = {
  'sale.cash': "Penjualan tunai",
  'sale.quantity': "Jumlah",
  'sale.tender': "Uang diterima (Rupiah)",
  'sale.confirmBody': "Konfirmasi penjualan setelah menerima uang tunai. Total dan kembalian ditetapkan saat penjualan disimpan.",
  'sale.pendingBody': "Hasil penjualan belum terkonfirmasi. Coba lagi dengan transaksi yang sama; jangan muat ulang atau tutup tab sebelum hasilnya diketahui.",
  'sale.pendingTitle': "Penjualan belum terkonfirmasi",
  'sale.resume': "Lanjutkan penjualan tertunda",
  'sale.retry': "Periksa / ulangi transaksi yang sama",
  'sale.post': "Konfirmasi pembayaran tunai",
  'sale.posting': "Memproses pembayaran…",
  'sale.detail': "Detail penjualan",
  'sale.loading': "Memuat penjualan…",
  'sale.posted': "Penjualan tersimpan",
  'sale.reversed': "Penjualan dibatalkan dan refund tercatat",
  'sale.reference': "Referensi penjualan",
  'sale.total': "Total",
  'sale.change': "Kembalian",
  'sale.refund': "Refund tunai",
  'sale.reverse': "Batalkan penjualan",
  'sale.reverseBody': "Pembatalan mencatat refund tunai penuh dan mempertahankan riwayat penjualan. Pastikan uang dikembalikan kepada pembeli.",
  'sale.reason': "Alasan pembatalan",
  'sale.reverseConfirm': "Konfirmasi pembatalan dan refund",
  'sale.reversing': "Memproses pembatalan…",
  'sale.refresh': "Periksa status terbaru",
  'sale.missing': "Penjualan tidak ditemukan di ruang usaha ini.",
  'sale.alreadyReversed': "Penjualan sudah dibatalkan. Periksa status terbaru sebelum melanjutkan.",
  'sale.conflict': "Transaksi berbeda menggunakan referensi yang sama. Jangan ulangi sebagai penjualan baru sebelum transaksi awal diperiksa.",
  'sale.insufficient': "Uang tunai belum mencukupi total penjualan. Periksa jumlah uang yang diterima.",
  'catalog.missing': "Item tidak ditemukan di ruang usaha ini.",
  'catalog.unsellable': "Item belum memiliki harga jual yang aktif.",
  'catalog.new': 'Tambah item',
  'catalog.name': 'Nama item',
  'catalog.price': 'Harga (Rupiah)',
  'catalog.priceHelp': 'Bilangan bulat positif. Kosongkan untuk item yang belum dijual.',
  'catalog.save': 'Simpan item',
  'catalog.saving': 'Menyimpan…',
  'catalog.detail': 'Detail item',
  'catalog.loading': 'Memuat item…',
  'catalog.unpriced': 'Belum memiliki harga jual',
  'root.loading': 'Memuat ruang usaha…',
  'root.new': 'Buat ruang usaha pertama',
  'root.newBody': 'Beri nama ruang usaha Anda untuk mulai menggunakan MiawPOS.',
  'root.name': 'Nama ruang usaha',
  'root.nameHelp': 'Maksimal 200 karakter.',
  'root.create': 'Buat ruang usaha',
  'root.creating': 'Membuat…',
  'root.check': 'Periksa ruang usaha yang sudah dibuat',
  'root.select': 'Pilih ruang usaha',
  'root.switch': 'Ganti ruang usaha',
  'root.workspace': 'Ruang usaha',
  'root.open': 'Buka ruang usaha',
  'root.ready': 'Ruang usaha Anda siap.',
  'app.name': 'MiawPOS',
  'app.caption': 'Ruang kerja Anda',
  'locale.label': 'Bahasa / Language',
  'locale.shortLabel': 'Bahasa',
  'login.title': 'Masuk ke MiawPOS',
  'login.google': 'Lanjutkan dengan Google',
  'session.loading': 'Memeriksa sesi Anda…',
  'session.title': 'Akun Anda',
  'session.description': 'Anda telah masuk ke MiawPOS.',
  'session.active': 'Sesi aktif',
  'session.accountId': 'ID akun',
  'session.details': 'Informasi akun',
  'session.detailsDescription': 'Identitas akun yang terhubung saat ini.',
  'session.placeholderTitle': 'Anda sudah terhubung',
  'session.placeholderBody': 'Akses akun sudah tersedia. Fitur operasional belum tersedia di versi ini.',
  'session.logout': 'Keluar',
  'session.loggingOut': 'Keluar…',
  'session.sharedDevice': 'Selesai menggunakan perangkat bersama? Keluar dari akun Anda.',
  'nav.account': 'Akun',
  'nav.label': 'Navigasi utama',
  'nav.menu': 'Buka navigasi',
  'nav.close': 'Tutup navigasi',
  'nav.skip': 'Lewati ke konten',
  'notFound.title': 'Halaman tidak ditemukan',
  'notFound.body': 'Periksa alamat halaman atau kembali ke akun Anda.',
  'notFound.back': 'Kembali',
  'action.retry': 'Coba lagi',
  'feedback.login.title': 'Belum dapat masuk',
  'feedback.login.body': 'Belum dapat terhubung dengan Google. Silakan coba lagi.',
  'feedback.expired.title': 'Sesi telah berakhir',
  'feedback.expired.body': 'Masuk kembali untuk melanjutkan.',
  'feedback.logout.title': 'Anda telah keluar',
  'feedback.logout.body': 'Sesi akun Anda sudah diakhiri.',
  'feedback.denied.title': 'Akses tidak diizinkan',
  'feedback.denied.body': 'Anda tidak memiliki akses untuk tindakan ini. Hubungi pengelola Anda.',
  'feedback.unavailable.title': 'Tindakan belum tersedia',
  'feedback.unavailable.body': 'Tindakan ini tidak tersedia saat ini. Hubungi pengelola Anda.',
  'feedback.validation.title': 'Periksa isian Anda',
  'feedback.validation.body': 'Lengkapi atau perbaiki isian yang ditandai.',
  'feedback.required': 'Isian ini wajib diisi.',
  'feedback.invalid': 'Masukkan nilai yang valid.',
  'feedback.network.title': 'Tidak dapat terhubung',
  'feedback.network.body': 'Periksa koneksi Anda, lalu coba lagi. Tindakan belum dapat dikonfirmasi.',
  'feedback.request.title': 'Tindakan tidak dapat dilakukan',
  'feedback.request.body': 'Periksa isian Anda atau hubungi pengelola.',
  'feedback.system.title': 'Terjadi gangguan',
  'feedback.system.body': 'Tindakan belum dapat dikonfirmasi. Coba lagi atau hubungi pengelola.',
  'feedback.contract.title': 'Respons tidak dapat diproses',
  'feedback.contract.body': 'Hubungi pengelola jika masalah berlanjut. Tindakan belum dapat dikonfirmasi.',
  'feedback.reference': 'Referensi bantuan: {requestId}',
} as const
