export const idID = {
  'app.name': 'MiawPOS',
  'app.caption': 'Ruang kerja Anda',
  'locale.label': 'Bahasa / Language',
  'locale.shortLabel': 'Bahasa',
  'login.title': 'Masuk ke MiawPOS',
  'login.google': 'Lanjutkan dengan Google',
  'session.loading': 'Memeriksa sesi Anda…',
  'session.title': 'Akun Anda',
  'session.description': 'Anda telah masuk ke MiawPOS.',
  'session.active': 'Sesi aktif',
  'session.accountId': 'ID akun',
  'session.details': 'Informasi akun',
  'session.detailsDescription': 'Identitas akun yang terhubung saat ini.',
  'session.placeholderTitle': 'Anda sudah terhubung',
  'session.placeholderBody': 'Akses akun sudah tersedia. Fitur operasional belum tersedia di versi ini.',
  'session.logout': 'Keluar',
  'session.loggingOut': 'Keluar…',
  'session.sharedDevice': 'Selesai menggunakan perangkat bersama? Keluar dari akun Anda.',
  'nav.account': 'Akun',
  'nav.label': 'Navigasi utama',
  'nav.menu': 'Buka navigasi',
  'nav.close': 'Tutup navigasi',
  'nav.skip': 'Lewati ke konten',
  'notFound.title': 'Halaman tidak ditemukan',
  'notFound.body': 'Periksa alamat halaman atau kembali ke akun Anda.',
  'notFound.back': 'Kembali',
  'action.retry': 'Coba lagi',
  'feedback.login.title': 'Belum dapat masuk',
  'feedback.login.body': 'Belum dapat terhubung dengan Google. Silakan coba lagi.',
  'feedback.expired.title': 'Sesi telah berakhir',
  'feedback.expired.body': 'Masuk kembali untuk melanjutkan.',
  'feedback.logout.title': 'Anda telah keluar',
  'feedback.logout.body': 'Sesi akun Anda sudah diakhiri.',
  'feedback.denied.title': 'Akses tidak diizinkan',
  'feedback.denied.body': 'Anda tidak memiliki akses untuk tindakan ini. Hubungi pengelola Anda.',
  'feedback.unavailable.title': 'Tindakan belum tersedia',
  'feedback.unavailable.body': 'Tindakan ini tidak tersedia saat ini. Hubungi pengelola Anda.',
  'feedback.validation.title': 'Periksa isian Anda',
  'feedback.validation.body': 'Lengkapi atau perbaiki isian yang ditandai.',
  'feedback.required': 'Isian ini wajib diisi.',
  'feedback.invalid': 'Masukkan nilai yang valid.',
  'feedback.network.title': 'Tidak dapat terhubung',
  'feedback.network.body': 'Periksa koneksi Anda, lalu coba lagi. Tindakan belum dapat dikonfirmasi.',
  'feedback.request.title': 'Tindakan tidak dapat dilakukan',
  'feedback.request.body': 'Periksa isian Anda atau hubungi pengelola.',
  'feedback.system.title': 'Terjadi gangguan',
  'feedback.system.body': 'Tindakan belum dapat dikonfirmasi. Coba lagi atau hubungi pengelola.',
  'feedback.contract.title': 'Respons tidak dapat diproses',
  'feedback.contract.body': 'Hubungi pengelola jika masalah berlanjut. Tindakan belum dapat dikonfirmasi.',
  'feedback.reference': 'Referensi bantuan: {requestId}',
} as const
