import { test, expect } from '@playwright/test'
import { checkLayout, checkStorage, login } from './helpers'

test('responsive navigation, keyboard input, locale, and reflow smoke', async ({ page }, testInfo) => {
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'Masuk ke MiawPOS' })).toBeVisible()
  await checkLayout(page)
  await page.getByLabel('Bahasa / Language').focus()
  await page.keyboard.press('Tab')
  const google = page.getByRole('link', { name: 'Lanjutkan dengan Google' })
  await expect(google).toBeFocused()
  expect(await google.evaluate(element => element.matches(':focus-visible'))).toBe(true)
  await page.screenshot({ path: `test-results/${testInfo.project.name}-login.png`, fullPage: true })
  await login(page)
  await checkLayout(page)
  if (testInfo.project.name === 'mobile') {
    await page.getByRole('button', { name: 'Buka navigasi' }).click()
    await expect(page.locator('#mobile-nav').getByRole('link', { name: 'Akun', exact: true })).toBeVisible()
    await page.locator('#mobile-nav').getByRole('link', { name: 'Akun', exact: true }).click()
  }
  await page.getByLabel('Bahasa / Language').click()
  await page.getByRole('option', { name: 'English' }).click()
  await expect(page.getByRole('heading', { name: 'Your account' })).toBeVisible()
  await checkLayout(page)
  await page.screenshot({ path: `test-results/${testInfo.project.name}-account.png`, fullPage: true })
  await page.getByRole('link', { name: 'Open workspace' }).click()
  // The tablet chain created two memberships. A fresh client must ask, not remember.
  await expect(page.getByRole('heading', { name: 'Choose a workspace' })).toBeVisible()
  await page.getByRole('button', { name: 'Warung R6', exact: true }).click()
  await page.getByRole('link', { name: 'Add item' }).click()
  await page.getByLabel('Item name').fill(`Coffee ${testInfo.project.name}`)
  await page.getByLabel('Price (Rupiah)').fill('18000')
  await page.getByRole('button', { name: 'Save item' }).click()
  await expect(page.getByRole('heading', { name: `Coffee ${testInfo.project.name}` })).toBeVisible()
  await checkLayout(page)
  await page.screenshot({ path: `test-results/${testInfo.project.name}-cash.png`, fullPage: true })
  await page.setViewportSize({ width: 320, height: 900 })
  await checkLayout(page)
  await page.getByLabel('Cash received (Rupiah)').fill('20000')
  await page.getByRole('button', { name: 'Confirm cash payment' }).click()
  await expect(page.getByText('Sale posted', { exact: true })).toBeVisible()
  await checkLayout(page)
  await page.getByLabel('Reversal reason').fill('Responsive proof')
  await page.getByRole('button', { name: 'Confirm reversal and refund' }).click()
  await expect(page.getByText('Sale reversed and refund recorded', { exact: true })).toBeVisible()
  await checkLayout(page)
  await page.screenshot({ path: `test-results/${testInfo.project.name}-reversal-320.png`, fullPage: true })
  await page.getByRole('link', { name: 'Account', exact: true }).click()
  await page.getByRole('button', { name: 'Sign out', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Sign in to MiawPOS' })).toBeVisible()
  await checkLayout(page)
  await checkStorage(page)
})
